WARNS_UNTIL_ACTION = 3
ACTION_ON_WARN_LIMIT = "mute"
ACTION_ON_WARN_DURATION_DAYS = 7
DEFAULT_WARN_DURATION_DAYS = 30

DEFAULT_BAN_DAYS = 7
DEFAULT_MUTE_DAYS = 1
DEFAULT_VOICE_MUTE_DAYS = 1
DEFAULT_BLACKLIST_DAYS = 600

ACTION_ON_WARN_DURATION_SECONDS = ACTION_ON_WARN_DURATION_DAYS * 86400
DEFAULT_WARN_DURATION_SECONDS = DEFAULT_WARN_DURATION_DAYS * 86400
DEFAULT_BAN_SECONDS = DEFAULT_BAN_DAYS * 86400
DEFAULT_MUTE_SECONDS = DEFAULT_MUTE_DAYS * 86400
DEFAULT_VOICE_MUTE_SECONDS = DEFAULT_VOICE_MUTE_DAYS * 86400
DEFAULT_BLACKLIST_SECONDS = DEFAULT_BLACKLIST_DAYS * 86400